---
repository:
  name: cbrgm/pr-size-labeler-action
  description: Automates the generation of project files and templates for repositories (and others) based on customizable YAML configurations.
  homepage: https://cbrgm.net
  topics: gihub-actions, github, action, go, size, pull-requests, labels

  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

  allow_update_branch: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - testing
      enforce_admins: false
      restrictions:
        apps:
          - cbrgm[bot]
        users: []
...
