name: PR Size Labeler

on:
  pull_request:
jobs:
  pr-size-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Label PR based on size
        uses: cbrgm/pr-size-labeler-action@main
        with:
          config_file_path: '.github/pull-request-size.yml'  # Path to the size labeler configuration file
          github_repository: ${{ github.repository }}  # The GitHub repository where the pull request was made
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          github_pr_number: ${{ github.event.number }}  # The number of the pull request
